// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAq1eOqx1HXc6OQvRuy9qqI6M-V3fpBhrI',
    appId: '1:63579270435:web:3e0b5f78098475a6657096',
    messagingSenderId: '63579270435',
    projectId: 'agrovale-app',
    authDomain: 'agrovale-app.firebaseapp.com',
    storageBucket: 'agrovale-app.firebasestorage.app',
    measurementId: 'G-H0C4E5YRSE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsk9PQRnsHcyOOCCfHk4Kc2UPLEWTfzZU',
    appId: '1:63579270435:android:6e201609899e6c0e657096',
    messagingSenderId: '63579270435',
    projectId: 'agrovale-app',
    storageBucket: 'agrovale-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANQRLSiXYDPr9ynZ13X_h-6dMwkY7SiHk',
    appId: '1:63579270435:ios:19d9083af87f3fd1657096',
    messagingSenderId: '63579270435',
    projectId: 'agrovale-app',
    storageBucket: 'agrovale-app.firebasestorage.app',
    iosBundleId: 'br.com.webanthony.projetointegrado',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAq1eOqx1HXc6OQvRuy9qqI6M-V3fpBhrI',
    appId: '1:63579270435:web:7f25e39059ab11b5657096',
    messagingSenderId: '63579270435',
    projectId: 'agrovale-app',
    authDomain: 'agrovale-app.firebaseapp.com',
    storageBucket: 'agrovale-app.firebasestorage.app',
    measurementId: 'G-2N16G954XF',
  );
}
